for iRealization = 1:tParameters.iNumberOfRealizations;
	%
	tRealizationGeneration.afActualCoefficients =	...
			randn( size(tComputer.afEigenvalues) )	...
		.*	sqrt( tComputer.afEigenvalues );
	%
	tRealizationGeneration.ffActualRealization =		...
		GenerateSignalFromEigenfunctionsWeights(		...
			tComputer.ffEigenfunctions,					...
			tComputer.tInputDomain.iNumberOfDimensions,	...
			tRealizationGeneration.afActualCoefficients	);
	%
	PlotRealization(	tComputer.tInputDomain,						...
						tRealizationGeneration.ffActualRealization,	...
						iRealization	);
	%
    tComputer.ExportRealizationIntoTxtFiles(		...
		tParameters,								...
		tRealizationGeneration.ffActualRealization,	...
		iRealization );
    %
end;%
