function [	fEstimatedGamma_CC,					...
			fEstimatedE,						...
			fEstimatedGamma,					...
			afRs_CC,							...
			aafRTildes			] =				...
				EstimateHyperparameters(		...
					ffInputLocations,			...
					iiInputLocationsIndexes,	...
					afMeasurements,				...
					afPotentialGammas,			...
					EA,							...
					tKernelParameters			)
	%
	% --------------------------------------
	% first part = regularization parameters
	%
	% centralized correct
	[	fEstimatedGamma_CC,														...
		afRs_CC			] =														...
			EstimateRegularizationParametersWithCentralizedCorrectSURE(			...
				ffInputLocations,												...
				iiInputLocationsIndexes,										...
				afMeasurements,													...
				afPotentialGammas,												...
				EA,																...
				tKernelParameters												);
	%
% 	% distributed approximated
% 	[	fEstimatedGamma_DA,														...
% 		afRTildes_DA			] =												...
% 			EstimateRegularizationParametersWithDistributedApproximatedSURE(	...
% 				ffInputLocations,												...
% 				iiInputLocationsIndexes,										...
% 				afMeasurements,													...
% 				afPotentialGammas,												...
% 				EA,																...
% 				tKernelParameters												);
	%
	% DEBUG
% 	figure(1)
% 	loglog(afPotentialGammas, afRs_CC, '--r');
% 	hold on
% 	loglog(afPotentialGammas, afRTildes_DA, '-b');
% 	hold off
% 	legend('correct', 'approximated', 'Location', 'northoutside');
% 	pause
	%
	% --------------------------------------
	% second part = number of eigenfunctions
	%
	[	fEstimatedE,															...
		fEstimatedGamma,														...
		aafRTildes			] =													...
			EstimateEWithDistributedApproximatedSURE(							...
				ffInputLocations,												...
				iiInputLocationsIndexes,										...
				afMeasurements,													...
				afPotentialGammas,												...
				EA,																...
				tKernelParameters												);
	%
	% DEBUG
% 	figure(2)
% 	surf(afPotentialGammas, 1:EA, aafRTildes);
% 	set(gca, 'XScale', 'log', 'ZScale', 'log');
% 	xlabel('gammas')
% 	ylabel('E')
% 	zlabel('Rtilde')
	%
end % function


