function [	ffEstimatedProcess,					...
			afEstimatedCoefficients	]	=		...
				EstimateProcessA(				...
					ffInputLocations,			...
					GA,							...
					aafKForRegression,			...
					afMeasurements,				...
					gamma,						...
					sigma2,						...
					E,							...
					tNystromComputer			)
	%
	% for readability
	M = numel( afMeasurements );
	%
	afEstimatedCoefficients =									...
		inv (													...
				( GA' * GA / M )								...
				+												...
				gamma * ( sigma2 / M ) * aafKForRegression		...
			)													...
		*	(													...
				GA' * afMeasurements / M						...
			);
	%
	ffEstimatedProcess = GenerateSamplesFromBasisfunctionsWeights(	...
			tNystromComputer,										...
			afEstimatedCoefficients,								...
			ffInputLocations										);
	%
end % function

