function [	ffEstimatedProcess,					...
			afEstimatedCoefficients	]	=		...
				EstimateProcessB(				...
					ffInputLocations,			...
					G,							...
					aafKForRegression,			...
					afMeasurements,				...
					gamma,						...
					sigma2,						...
					E,							...
					tNystromComputer			)
	%
	% computation of the auxiliary matrices
% 	Lambda	= diag( tNystromComputer.afEigenvalues(1:E) );
	M		= numel( afMeasurements );
	%
	afEstimatedCoefficients =									...
		inv (													...
				tNystromComputer.aafExpectedGGM(1:E, 1:E)		...
				+												...
				gamma * ( sigma2 / M ) * aafKForRegression		...
			)													...
		*	(													...
				G' * afMeasurements / M							...
			);
	%
	ffEstimatedProcess = GenerateSamplesFromBasisfunctionsWeights(	...
			tNystromComputer,										...
			afEstimatedCoefficients,								...
			ffInputLocations										);
	%
end %

