strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_SURE_FA.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessSUREFA,			...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_SURE_FA_Nystrom.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessSUREFANystrom,	...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_SURE_FB.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessSUREFB,			...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_SURE_FB_Nystrom.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessSUREFBNystrom,	...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_Oracle_FA.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessOracleFA,			...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_estimated_realization_Oracle_FB.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedProcessOracleFB,			...
	5,									... sampling in X
	5									);% sampling in Y
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/1D_Test_RSSs_vs_SURE_Risks_FA.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	log10(afPotentialGammasFA)',	...
		afTestRSSsFA,					...
		afTestRSSsFANystrom,			...
		afTestFitsFA,					...
		afTestFitsFANystrom,			...
		afSURERisksFA,					...
		afSURERisksFANystrom	],		...
	[	{'log10PotentialGammas'},		...
		{'afTestRSSsFA'},				...
		{'afTestRSSsFANystrom'},		...
		{'afTestFitsFA'},				...
		{'afTestFitsFANystrom'},		...
		{'afSURERisksFAtimes'},			...
		{'afSURERisksFAtimesNystrom'}	]);
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/1D_Test_RSSs_vs_SURE_Risks_FB.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	aiPotentialEs',					...
		aafTestRSSsFB',					...
		aafTestRSSsFBNystrom',			...
		aafTestFitsFB',					...
		aafTestFitsFBNystrom',			...
		aafSURERisksFB',				...
		aafSURERisksFBNystrom'	],		...
	[	{'E'},							...
		{'afTestRSSsFB'},				...
		{'afTestRSSsFBNystrom'},		...
		{'afTestFitsFB'},				...
		{'afTestFitsFBNystrom'},		...
		{'afSURERisksFBtimes'},			...
		{'afSURERisksFBtimesNystrom'}	]);
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_realization_training_measurements.txt');
MatlabToTikZ.Export3DScatterplot(		...
	strFilename,						...
	ffTrainingInputLocations,			...
	afTrainingMeasurements				);
%
strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_realization_test_measurements.txt');
MatlabToTikZ.Export3DScatterplot(		...
	strFilename,						...
	ffTestInputLocations,				...
	afTestMeasurements					);
%
% strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_Test_RSSs_FB.txt');
% MatlabToTikZ.ExportSurfplot(			...
% 	strFilename,						...
% 	log10(afPotentialGammasFB),			...
% 	aiPotentialEs,						...
% 	aafTestRSSsFB,						...
% 	1,									... sampling in X
% 	1									);% sampling in Y
% %
% strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/2D_SURE_Risks_FB.txt');
% MatlabToTikZ.ExportSurfplot(			...
% 	strFilename,						...
% 	log10(afPotentialGammasFB),			...
% 	aiPotentialEs,						...
% 	aafSURERisksFB,						...
% 	1,									... sampling in X
% 	1									);% sampling in Y




% diary('../../ArticleJournal/Data/ColoradoRain/diary.txt');
% diary on;
% fEstimatedGammaSUREFA
% fEstimatedGammaOracleFA
% iEstimatedESUREFB
% iEstimatedEOracleFB
% fEstimatedGammaSUREFB
% fEstimatedGammaOracleFB
% boundA
% boundB
% diary off;


strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/scatter_RSS_oracle_vs_Sure_FA.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	afRSSOracleFA',					...
		afRSSOracleFANystrom',			...
		afRSSSureFA',					...
		afRSSSureFANystrom'	],			...
	[	{'RSSOracleFA'},				...
		{'RSSOracleFANystrom'},			...
		{'RSSSureFA'},					...
		{'RSSSureFANystrom'}]			);


strFilename = sprintf('../../ArticleJournal/Data/ColoradoRain/scatter_RSS_oracle_vs_Sure_FB.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	afRSSOracleFB',					...
		afRSSOracleFBNystrom',			...
		afRSSSureFB',					...
		afRSSSureFBNystrom'	],			...
	[	{'RSSOracleFB'},				...
		{'RSSOracleFBNystrom'},			...
		{'RSSSureFB'},					...
		{'RSSSureFBNystrom'}]			);

