strFilename = sprintf('../../ArticleJournal/Data/UCICPUPerformance/1D_Test_RSSs_vs_SURE_Risks_FA.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	log10(afPotentialGammasFA)',	...
		afTestRSSsFA,					...
		afTestFitsFA,					...
		afSURERisksFA	],				...
	[	{'log10PotentialGammas'},		...
		{'afTestRSSsFA'},				...
		{'afTestFitsFA'},				...
		{'afSURERisksFAtimes'}			]);
figure(1)
plot(log10(afPotentialGammasFA), afTestRSSsFA, '-r');
hold on;
plot(log10(afPotentialGammasFA), afTestFitsFA, '-k');
plot(log10(afPotentialGammasFA), afSURERisksFA, '-b');
hold off;
legend('test RSS FA', 'test fits FA', 'SURE risks FA');


strFilename = sprintf('../../ArticleJournal/Data/UCICPUPerformance/1D_Test_RSSs_vs_SURE_Risks_FB.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	aiPotentialEs',					...
		aafTestRSSsFB',					...
		aafTestFitsFB',					...
		aafSURERisksFB'			],		...
	[	{'E'},							...
		{'afTestRSSsFB'},				...
		{'afTestFitsFB'},				...
		{'afSURERisksFBtimes'}			]);
figure(2)
subplot(3,1,1)
plot(aiPotentialEs, aafTestRSSsFB, '-r');
legend('test RSS FB');
subplot(3,1,2)
plot(aiPotentialEs, aafTestFitsFB, '-k');
legend('test fits FB');
subplot(3,1,3)
plot(aiPotentialEs, aafSURERisksFB, '-b');
hold off;
legend('SURE risks FB');


strFilename = sprintf('../../ArticleJournal/Data/UCICPUPerformance/scatter_RSS_oracle_vs_Sure_FA.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	fRSSOracleFA',					...
		fRSSSureFA'		],				...
	[	{'RSSOracleFA'},				...
		{'RSSSureFA'}		]			);


strFilename = sprintf('../../ArticleJournal/Data/UCICPUPerformance/scatter_RSS_oracle_vs_Sure_FB.txt');
MatlabToTikZ.ExportLineplot(			...
	strFilename,						...
	[	fRSSOracleFB',					...
		fRSSSureFB'		],				...
	[	{'RSSOracleFB'},				...
		{'RSSSureFB'}		]			);


% fprintf('Fit Oracle FA = %.3f  \t Fit SURE FA = %.3f \n', afTestFitsFA(iGammaIndexOracleFA), afTestFitsFA(iGammaIndexSUREFA));
% fprintf('Fit Oracle FB = %.3f  \t Fit SURE FB = %.3f \n', aafTestFitsFB(iGammaIndexOracleFA, iEIndexOracleFB), aafTestFitsFB(iGammaIndexSUREFB, iEIndexSUREFB));

