strFilename = sprintf('../../ArticleJournal/Data/UCI/KPIsFA.txt');
MatlabToTikZ.ExportLineplot(								...
	strFilename,											...
	aafPerformanceIndexesFA, 								...
	[	{'fBestTestRSSFAPlusOracle'},						...
		{'fCorrespondingTestRSSFAPlusSURE'},				...
		{'fBestGammaAccordingToOracleForFAForRSS'},			...
		{'fBestGammaAccordingToSUREForFAForRSS'},			...
		{'iBestKernelTypeForTestRSSFAPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestRSSFAPlusOracle'},	...
		{'fBestTestFitFAPlusOracle'},						...
		{'fCorrespondingTestFitFAPlusSURE'},				...
		{'fBestGammaAccordingToOracleForFAForFit'},			...
		{'fBestGammaAccordingToSUREForFAForFit'},			...
		{'iBestKernelTypeForTestFitFAPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestFitFAPlusOracle'},	...
		{'fBestTestCEFAPlusOracle'},						...
		{'fCorrespondingTestCEFAPlusSURE'},					...
		{'fBestGammaAccordingToOracleForFAForCE'},			...
		{'fBestGammaAccordingToSUREForFAForCE'},			...
		{'iBestKernelTypeForTestCEFAPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestCEFAPlusOracle'}	]);

strFilename = sprintf('../../ArticleJournal/Data/UCI/KPIsFB.txt');
MatlabToTikZ.ExportLineplot(								...
	strFilename,											...
	aafPerformanceIndexesFB, 								...
	[	{'fBestTestRSSFBPlusOracle'},						...
		{'fCorrespondingTestRSSFBPlusSURE'},				...
		{'fBestGammaAccordingToOracleForFBForRSS'},			...
		{'fBestGammaAccordingToSUREForFBForRSS'},			...
		{'iBestEAccordingToOracleForFBForRSS'},				...
		{'iBestEAccordingToSUREForFBForRSS'},				...
		{'iBestKernelTypeForTestRSSFBPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestRSSFBPlusOracle'},	...
		{'fBestTestFitFBPlusOracle'},						...
		{'fCorrespondingTestFitFBPlusSURE'},				...
		{'fBestGammaAccordingToOracleForFBForFit'},			...
		{'fBestGammaAccordingToSUREForFBForFit'},			...
		{'iBestEAccordingToOracleForFBForFit'},				...
		{'iBestEAccordingToSUREForFBForFit'},				...
		{'iBestKernelTypeForTestFitFBPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestFitFBPlusOracle'},	...
		{'fBestTestCEFBPlusOracle'},						...
		{'fCorrespondingTestCEFBPlusSURE'},					...
		{'fBestGammaAccordingToOracleForFBForCE'},			...
		{'fBestGammaAccordingToSUREForFBForCE'},			...
		{'iBestEAccordingToOracleForFBForCE'},				...
		{'iBestEAccordingToSUREForFBForCE'},				...
		{'iBestKernelTypeForTestCEFBPlusOracle'},			...
		{'iBestKernelVarianceIndexForTestCEFBPlusOracle'}	]);


save('../../ArticleJournal/Data/UCI/KPIs.mat', 'aafPerformanceIndexesFA', 'aafPerformanceIndexesFB');

