M					= 100;
E					= 30;
afPotentialGammas	= logspace(-20,4,100);


[ffTrueProcess, afTrueParameters] = GenerateTrueProcess( tKernelParameters );
[ffInputLocations, iiInputLocationsIndexes, afMeasurements] = MeasureProcess( ffTrueProcess, M, tKernelParameters, atAgents );

gammaSURE	= EstimateGammaWithDistributedSURE(		...
					ffInputLocations,				...
					iiInputLocationsIndexes,		...
					afMeasurements,					...
					afPotentialGammas,				...
					E,								...
					tKernelParameters				)

[ ffEstimatedFA, afEstimatedCoefficientsFA ] = EstimateProcessA( iiInputLocationsIndexes, afMeasurements, gammaSURE, E, tKernelParameters );


% DEBUG
figure(1)
surf(ffTrueProcess)
figure(2)
surf(ffEstimatedFA)


strFilename = sprintf('../../ArticleJournal/Data/3DSurface/2D_realization.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffTrueProcess,						...
	1,									... sampling in X
	1									);% sampling in Y
strFilename = sprintf('../../ArticleJournal/Data/3DSurface/2D_estimated_realization.txt');
MatlabToTikZ.ExportSurfplot(			...
	strFilename,						...
	tKernelParameters.afDomainXAxis,	...
	tKernelParameters.afDomainYAxis,	...
	ffEstimatedFA,				...
	1,									... sampling in X
	1									);% sampling in Y
strFilename = sprintf('../../ArticleJournal/Data/3DSurface/2D_realization_measurements.txt');
MatlabToTikZ.Export3DScatterplot(		...
	strFilename,						...
	ffInputLocations,					...
	afMeasurements						);

