aafPerformanceIndexesFA( iUCIDatasetIndex, : ) =		...
	[	fBestTestRSSFAPlusOracle,						...
		fCorrespondingTestRSSFAPlusSURE,				...
		fBestGammaAccordingToOracleForFAForRSS,			...
		fBestGammaAccordingToSUREForFAForRSS,			...
		iBestKernelTypeForTestRSSFAPlusOracle,			...
		iBestKernelVarianceIndexForTestRSSFAPlusOracle,	...
		fBestTestFitFAPlusOracle,						...
		fCorrespondingTestFitFAPlusSURE,				...
		fBestGammaAccordingToOracleForFAForFit,			...
		fBestGammaAccordingToSUREForFAForFit,			...
		iBestKernelTypeForTestFitFAPlusOracle,			...
		iBestKernelVarianceIndexForTestFitFAPlusOracle,	...
		fBestTestCEFAPlusOracle,						...
		fCorrespondingTestCEFAPlusSURE,					...
		fBestGammaAccordingToOracleForFAForCE,			...
		fBestGammaAccordingToSUREForFAForCE,			...
		iBestKernelTypeForTestCEFAPlusOracle,			...
		iBestKernelVarianceIndexForTestCEFAPlusOracle	];

aafPerformanceIndexesFB( iUCIDatasetIndex, : ) =		...
	[	fBestTestRSSFBPlusOracle,						...
		fCorrespondingTestRSSFBPlusSURE,				...
		fBestGammaAccordingToOracleForFBForRSS,			...
		fBestGammaAccordingToSUREForFBForRSS,			...
		iBestEAccordingToOracleForFBForRSS,				...
		iBestEAccordingToSUREForFBForRSS,				...
		iBestKernelTypeForTestRSSFBPlusOracle,			...
		iBestKernelVarianceIndexForTestRSSFBPlusOracle,	...
		fBestTestFitFBPlusOracle,						...
		fCorrespondingTestFitFBPlusSURE,				...
		fBestGammaAccordingToOracleForFBForFit,			...
		fBestGammaAccordingToSUREForFBForFit,			...
		iBestEAccordingToOracleForFBForFit,				...
		iBestEAccordingToSUREForFBForFit,				...
		iBestKernelTypeForTestFitFBPlusOracle,			...
		iBestKernelVarianceIndexForTestFitFBPlusOracle,	...
		fBestTestCEFBPlusOracle,						...
		fCorrespondingTestCEFBPlusSURE,					...
		fBestGammaAccordingToOracleForFBForCE,			...
		fBestGammaAccordingToSUREForFBForCE,			...
		iBestEAccordingToOracleForFBForCE,				...
		iBestEAccordingToSUREForFBForCE,				...
		iBestKernelTypeForTestCEFBPlusOracle,			...
		iBestKernelVarianceIndexForTestCEFBPlusOracle	];

