function strID = GetIDString( tNode, strDirectory )
	%
	strID =										...
		sprintf(								...
			'%sCNode_Consensus%d_Node%d.txt',	...
			strDirectory,						...
			tNode.iConsensusKind,				...
			tNode.iLabel						);
	%
end %
