function Export2DRealizationIntoTxtFiles(	tComputer,		...
											tParameters,	...
											aafRealization,	...
											iRealizationIndex )
	%
	%
	afStretchedXAxis =										...
		linspace(	tComputer.tInputDomain.afXAxis(1),		...
					tComputer.tInputDomain.afXAxis(end),	...
					tParameters.iNumberOfSamplesPerDimensionWhenExportingTxtFiles);
	%
	afStretchedYAxis =										...
		linspace(	tComputer.tInputDomain.afYAxis(1),		...
					tComputer.tInputDomain.afYAxis(end),	...
					tParameters.iNumberOfSamplesPerDimensionWhenExportingTxtFiles);
	%
	aafStretchedRealization =												...
		Stretch2DSignal(	aafRealization,									...
							tComputer.tInputDomain.afXAxis,					...
							tComputer.tInputDomain.afYAxis,					...
							afStretchedXAxis,								...
							afStretchedYAxis );
	%
	% compute the filename
	strFileName = sprintf(	'%s.Realization%d.txt',			...
							tParameters.strTxtFilesPrefix,	...
							iRealizationIndex				);
	%
	% open the file
	fid = fopen(strFileName, 'w');
	%
	% write the data -- X VARIES
	for iY = 1:numel(afStretchedXAxis);
		%
		for iX = 1:numel(afStretchedXAxis);
			%
			fprintf(fid,							...
					'%.10f %.10f %.10f\n',			...
					afStretchedXAxis( iX ),			...
					afStretchedYAxis( iY ),			...
					aafStretchedRealization(iX, iY) );
			%
		end;%
		%
		fprintf(fid, '\n');
		%
	end;%
	%
	% close the file
	fclose(fid);
	%
end %

