function Export2DMeasureIntoTxtFiles( tComputer, tParameters )
	%
	afStretchedXAxis =										...
		linspace(	tComputer.tInputDomain.afXAxis(1),		...
					tComputer.tInputDomain.afXAxis(end),	...
					tParameters.iNumberOfSamplesPerDimensionWhenExportingTxtFiles);
	%
	afStretchedYAxis =										...
		linspace(	tComputer.tInputDomain.afYAxis(1),		...
					tComputer.tInputDomain.afYAxis(end),	...
					tParameters.iNumberOfSamplesPerDimensionWhenExportingTxtFiles);
	%
	aafStretchedMeasure =													...
		Stretch2DSignal(	tComputer.tMeasure.ffDomainMeasure,				...
							tComputer.tInputDomain.afXAxis,					...
							tComputer.tInputDomain.afYAxis,					...
							afStretchedXAxis,								...
							afStretchedYAxis );
	%
	% compute the filename
	strFileName = sprintf( '%s.Measure.txt', tParameters.strTxtFilesPrefix );
	%
	% open the file
	fid = fopen(strFileName, 'w');
	%
	% write the data -- X VARIES
	for iY = 1:numel(afStretchedXAxis);
		%
		for iX = 1:numel(afStretchedXAxis);
			%
			fprintf(fid,							...
					'%.10f %.10f %.10f\n',			...
					afStretchedXAxis( iX ),			...
					afStretchedYAxis( iY ),			...
					aafStretchedMeasure(iX, iY) );
			%
		end;%
		%
		fprintf(fid, '\n');
		%
	end;%
	%
	% close the file
	fclose(fid);
	%
	%
end %
