function GenerateUniformMeasure( tGenerator )
	%
	%
	iNumberOfInputLocations =									...
			max( numel(tGenerator.tInputDomain.afXAxis), 1 )	...
		*	max( numel(tGenerator.tInputDomain.afYAxis), 1 )	...
		*	max( numel(tGenerator.tInputDomain.afZAxis), 1 );
	%
	%
	switch( tGenerator.tInputDomain.iNumberOfDimensions )
		%
		case 1
			tGenerator.ffDomainMeasure =						...
				ones( size(tGenerator.tInputDomain.afXAxis) )	...
				/												...
				iNumberOfInputLocations;
		%
		case 2
			tGenerator.ffDomainMeasure =								...
				ones(	numel(tGenerator.tInputDomain.afXAxis),			...
						numel(tGenerator.tInputDomain.afYAxis)	)		...
				/														...
				iNumberOfInputLocations;
		%
		case 3
			tGenerator.ffDomainMeasure =								...
				ones(	numel(tGenerator.tInputDomain.afXAxis),			...
						numel(tGenerator.tInputDomain.afYAxis),			...
						numel(tGenerator.tInputDomain.afZAxis)	)		...
				/														...
				iNumberOfInputLocations;
		%
		otherwise
			tGenerator.ffDomainMeasure = [];
		%
	end;%
	%
	%
end %
